version: "3"

services:
  sensor:
    build: ./docker/sensors
    image: digital-twin-sensor
    ports:
      - "1883"
  
  plc:
    build: ./docker/plc
    image: digital-twin-plc

  dashboard:
    build: ./docker/dashboard
    image: digital-twin-dashboard
    ports:
      - "5000:5000"

  mqtt-broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"

  dnp3-outstation:
    build: ./docker/dnp3
    image: digital-twin-dnp3
    ports:
      - "20000:20000"
