apiVersion: apps/v1
kind: Deployment
metadata:
  name: jensys
  namespace: digital-twin
  labels:
    app: jensys
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jensys
  template:
    metadata:
      labels:
        app: jensys
    spec:
      containers:
        - name: jensys
          image: nextphasedv29/jensys:latest
          imagePullPolicy: Always
          env:
            - name: MQTT_BROKER
              value: "mqtt-broker"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
