apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-broker
  namespace: digital-twin
  labels:
    app: mqtt-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-broker
  template:
    metadata:
      labels:
        app: mqtt-broker
    spec:
      containers:
        - name: mqtt-broker
          image: nextphasedv29/mqtt-broker:latest
          imagePullPolicy: Always
          # image: eclipse-mosquitto:2.0
          # imagePullPolicy: Never
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          volumeMounts:
            - name: config-volume
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
      volumes:
        - name: config-volume
          configMap:
            name: mosquitto-config  # Must match the ConfigMap in K8s/configmaps/
