apiVersion: apps/v1
kind: Deployment
metadata:
  name: plc
  namespace: digital-twin   
  labels:
    app: plc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plc
  template:
    metadata:
      labels:
        app: plc
    spec:
      containers:
        - name: plc
          image: plc:latest
          imagePullPolicy: Never
          env:
            - name: MQTT_BROKER
              value: "mqtt-broker"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
