# K8s/deployments/sensor-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor
  labels:
    app: sensor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor
  template:
    metadata:
      labels:
        app: sensor
    spec:
      containers:
      - name: sensor
        image: nextphasedv29/sensor:latest
        env:
        - name: MQTT_BROKER
          value: "mqtt-broker-service"
        - name: MQTT_TOPIC
          value: "sensors/temperature"
