apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor
  labels:
    app: sensor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor
  template:
    metadata:
      labels:
        app: sensor
    spec:
      containers:
        - name: sensor
          image: sensor:latest
          imagePullPolicy: Never
          env:
            - name: MQTT_BROKER
              value: "mqtt-broker"
