apiVersion: apps/v1
kind: Deployment
metadata:
  name: trane
  namespace: digital-twin
  labels:
    app: trane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trane
  template:
    metadata:
      labels:
        app: trane
    spec:
      containers:
        - name: trane
          image: trane:latest
          imagePullPolicy: Never
          env:
            - name: MQTT_BROKER
              value: "mqtt-broker"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
